### ISSUE TITLE
Cutting through the hierarchically nested individual through international levels

### ISSUE THREAD

**Issue by JeroenBosman** [Open-Scholarship-Strategy/site#18]
It think that in focusing on the individual-lab-institutional-national-international hierarchy of decision making levels we need to add other perspectives, especially ones that connect the lower levels (individual/lab) internationally. 

One reason is that culturally determined aspects of open science should be discussed at the field level, e.g. during international conferences.

Another reason is that you can create forces of learning, support and change by having international communities of open science practising researchers etc, because together the have the best insight into real life barriers and how to overcome them and they can create new realities that the national and institutional levels then have to include in their decision making. 

If we ignore these, then individuals and labs will feel on their own or may take approach of waiting for the institutions and national levels bodies to tell them what to do.

For the current version of the doc I suggest to at least mention the importance of international coalitions/communities of the lower levels for learning and sharing knowledge of OS practices, especially in varying cultural settings.

**Comment by Protohedgehog** [comment]
Have integrated this in several places now, good stuff.
