### ISSUE TITLE
Principles or values?

### ISSUE THREAD

**Issue by JeroenBosman** [Open-Scholarship-Strategy/site#19]
The document lists as principles: participation, equality, transparency, cognitive justice, collaboration, sharing, equity, and inclusivity. I would say these are _values_ and not so much principles. If you have these values your can make them into principles for something by making them part of _statements_.

Thus, I would suggest to call them core values rather than principles.

**Comment by Protohedgehog** [comment]
This is an excellent point. What I've done is broaden the categories to 'knowledge and practices' and 'principles and values' now to reflect this.
