### ISSUE TITLE
Link to charters overview

### ISSUE THREAD

**Issue by JeroenBosman** [Open-Scholarship-Strategy/site#20]
In the section:

"Availability of Open Scholarship charters and declarations.
This ever-growing range of high-level statements in support of openness (typically Open Access) offers internally consistent sets of goals and actions that are result of a lot of thinking and discussing."

You could link to the overview of charters available at: http://tinyurl.com/scholcomm-charters

**Comment by Protohedgehog** [comment]
Ah, this is a much nicer URL, thanks. It was already referenced in Section 3, but I've added it in here too now - thanks!
