### ISSUE TITLE
Being open to the limitations of openness

### ISSUE THREAD

**Issue by JeroenBosman** [Open-Scholarship-Strategy/site#21]
In the document I miss references of the dangers of not being open to the limitations of openness. In the section on challenges for the community regarding language and appearance I would include:

Enthusiasm for openness carries the danger of not being receptive to critique or not acknowledging that there are situations where the standard open practices have dangers. This may relate to privacy but also to data that being open could be captured by governments for surveillance or by companies for corporate interests (think data on indigenous plants, data showing how local groups or environmental groups work etc.). It also relates to being open to critique regarding the dangers of platform based economies and unequal relation in research cooperations.

**Comment by Protohedgehog** [comment]
Such a good point. I added it under the 'Lack of patience' point now, thanks!
