### ISSUE TITLE
Duplicate line in section 7.1

### ISSUE THREAD

**Issue by timkoder** [Open-Scholarship-Strategy/site#25]
On the first public draft, a bullet is duplicated in section 7.1:

Overcoming the misconception that Open Scholarship is anti-commercial and demonstrating a return on investment (e.g., Balasegaram et al., 2017; Hakoum et al., 2017).

Overcoming the misconception that Open Scholarship is anti-commercial/demonstrating return on investment (e.g., Balasegaram et al., 2017; Hakoum et al., 2017).

**Comment by Protohedgehog** [comment]
Got it, thanks!
