### ISSUE TITLE
Could we add a strong finish?

### ISSUE THREAD

**Issue by timkoder** [Open-Scholarship-Strategy/site#26]
Now that the framework is up in public, looking great, would it make sense to finish not with the Threats section, but with a much more future-looking, aspirational call to action?

**Comment by Protohedgehog** [comment]
Ah, yes, that's a good idea. What sort of thing do you propose?

**Comment by Protohedgehog** [comment]
Hey @timkoder, looking at this again now, will add a new 'Conclusions section' to this version. Contributions welcome!

**Comment by Protohedgehog** [comment]
Note that section 11 is now the Conclusions https://open-scholarship-strategy.github.io/site/#11-conclusions-

**Comment by Protohedgehog** [comment]
@timkoder I have now added a concluding section to this - thoughts?

**Comment by timkoder** [comment]
Hi Jon, nice job on the Conclusions. Sorry I didn't reply sooner. Can I challenge you to halve the length, to make it punchier? I've taken 100 words out in the attached, see what you think. Cheers, Tim
[Conclusion - TJK ed.docx](https://github.com/Open-Scholarship-Strategy/site/files/2805346/Conclusion.-.TJK.ed.docx)

**Comment by timkoder** [comment]
Hi Jon

Sorry for the delay. I have worked on the pharma info and conclusion - see what you think. I'm still travelling for work and am not used to Github, so have wimped out of editing straight in and instead sent you two attachments, and if it doesn't work in GitHub, they are also attached here.

Cheers, Tim
________________________________

**Comment by Protohedgehog** [comment]
Brilliant, thank you @timkoder! Will get this integrated right away :)

**Comment by Protohedgehog** [comment]
This was fab, thanks @timkoder! Also conveniently more in line with the new executive summary that @brembs added this evening. Good stuff! :)
