### ISSUE TITLE
New text for pharma industry status

### ISSUE THREAD

**Issue by timkoder** [Open-Scholarship-Strategy/site#27]
The bullet in section 4.2 is now out of date because there is one clinical preprint from pharma. It also looks odd to talk only about preprints. I have therefore given a little more context about the industry and some brief text about changes in open access, ORCID and preprints.
[2018-07-30 Open Scholarship Framework input from Tim.zip](https://github.com/Open-Scholarship-Strategy/site/files/2241537/2018-07-30.Open.Scholarship.Framework.input.from.Tim.zip)

**Comment by Protohedgehog** [comment]
This is great, thanks! You can also edit the text directly using Git's workflow if that's easier: https://github.com/Open-Scholarship-Strategy/site#how-to-contribute Saves having to switch back and forth between different documents in different formats :)

**Comment by Protohedgehog** [comment]
@timkoder do you think you could add this in to the latest version now, as we're updating that this month?

**Comment by Protohedgehog** [comment]
Ping @timkoder about this again, any thoughts?

**Comment by timkoder** [comment]
Hi Jon,

Sorry for the delay.
It’s good timing though - we’re holding a major round-table meeting of Open Pharma today and I should be well-informed to return to the strategy document after that.

Best wishes,

Tim

On 20 Jan 2019, at 09:24, Jon Tennant <notifications@github.com<mailto:notifications@github.com>> wrote:


Ping @timkoder<https://github.com/timkoder> about this again, any thoughts?

**Comment by Protohedgehog** [comment]
Fantastic, thanks @timkoder - looking forward to updates! :)

**Comment by timkoder** [comment]
Hi Jon, please find attached updated text. Not being used to Github working, and as it's close to deadline, rather than mess about in the file, I'm going to wimp out and ask you to insert the text please! Thanks, Tim
[2018-01-28 New text for section 4 pharma involvement.docx](https://github.com/Open-Scholarship-Strategy/site/files/2805262/2018-01-28.New.text.for.section.4.pharma.involvement.docx)

**Comment by Protohedgehog** [comment]
Brilliant, thank you @timkoder! Will get this integrated right away :)
