### ISSUE TITLE
localizations

### ISSUE THREAD

**Issue by tosteiner** [Open-Scholarship-Strategy/site#28]
@Protohedgehog Jon, I think you mentioned someone doing a translation of this to Spanish, right? I'm currently working on a German version - how would you like to have these implemented? atm, I'm simply working in a separate folder that mirrors the original structure but with German text...

**Comment by Protohedgehog** [comment]
*adds this to the list of things I need to buy @tosteiner beer for*

But yes, a Spanish version is in prep here: https://github.com/Open-Scholarship-Strategy/indexed#current-translations as well as an Indonesia adaptation, I believe.  If possible, best to use that existing directory structure for now? Open to suggestions of course. Will need to make sure that people doing the translations are all appropriately credited too. @lmatthia maybe this is something you might be able to help with too..?

**Comment by tosteiner** [comment]
@Protohedgehog I guess I'll close this issue for the time being - have now returned to picking up on the German translation, my ETA is to have this ready for the release of ver. 2.0

**Comment by Protohedgehog** [comment]
OK, that's awesome, thanks @tosteiner! If we could do a joint launch of ver.2 + the German version, that would be great. Do you need any assistance with the translations atm?
