### ISSUE TITLE
group of authors in zenodo? 

### ISSUE THREAD

**Issue by tosteiner** [Open-Scholarship-Strategy/site#30]
Not sure how the group feels about this?

**Comment by Protohedgehog** [comment]
Yeah, so the first release is out here: https://zenodo.org/record/1323437#.W2PrgtL7RPY

Ideally, all the members of the drafting committee would be pulled in to the main author list each time there was a new release, without me having to enter them manually. Any ideas on how to do this..?

**Comment by tosteiner** [comment]
haven't tried it myself, but Chris Gorgolewski has written a neat run-down on how this might work automatically:

* http://blog.chrisgorgolewski.org/2017/11/sharing-academic-credit-in-open-source.html
   * with file example here: https://github.com/nipy/nipype/blob/master/.zenodo.json

and I think sticking to the minimal content scheme of 
```
{
      "name": "Rabbit, Roger",
      "orcid": "0000-0002-468-1234"
}
```
would easily suffice, don't you think?

**Comment by Protohedgehog** [comment]
OK, awesome. Let's keep this in mind for the second release :) I want you all to be appropriately credited!

**Comment by Protohedgehog** [comment]
@tosteiner if we were to implement the above, do we need to create a new json file to accompany the other files here?

**Comment by tosteiner** [comment]
@Protohedgehog not sure about that myself - I guess this is connected to the repo metadata issue mentioned above which Simon wanted to check out, no?

**Comment by Protohedgehog** [comment]
Possibly. Let's give it a bash and see what happens :) 

Or, I don't mind just doing it manually.

**Comment by Protohedgehog** [comment]
Note that I'll have to do this now for the preprint submission to re #50

**Comment by tosteiner** [comment]
amazing job done by @Protohedgehog on doc finalization 👍  will close this here now

**Comment by Protohedgehog** [comment]
Awesome, thanks @tosteiner!
