### ISSUE TITLE
Preparations for ver.2? 

### ISSUE THREAD

**Issue by tosteiner** [Open-Scholarship-Strategy/site#38]
Hi Jon, hi all,

since I'm currently meddling around with the translation [over here](https://github.com/Open-Scholarship-Strategy/indexed/tree/master/translations/german), I was wondering how we're going about the second release that we announce for the end of this year... 

Do you guys think there's more changes needed, do we want to forward this to anyone interested in reviewing/adding stuff, etc ...?

**Comment by Protohedgehog** [comment]
Aha, excellent Q @tosteiner. I'll add it to my list of stuff to get done before Christmas.. hmm. I think there were some changes that were needed (a final paragraph), as well as just a general read through too.

**Comment by tosteiner** [comment]
Might prove worthwhile to directly link to the non-English language versions under the "file versions" section - will have a go at that later

**Comment by Protohedgehog** [comment]
Good minds think alike, was just about to do that! :)

**Comment by Protohedgehog** [comment]
Have added these links in now, and started generally updating the strategy.

**Comment by tosteiner** [comment]
will close this now, since elements have been sorted into other issues

**Comment by Protohedgehog** [comment]
Cool, thanks @tosteiner! Added in a link to the Indonesian version most recently too.
