### ISSUE TITLE
executive summary

### ISSUE THREAD

**Issue by brembs** [Open-Scholarship-Strategy/site#42]
This is a very thorough, detailed document that covers many aspects of open scholarship. I would argue that it deserves a summary, ideally one, but certainly no more than two pages of what short term actions stakeholders should strive towards. This could, e.g., be done by first ranking the lists in the very first section according to priority and then formulate the first three in each category to form a one page document.

Of course, this carries the risk of nobody reading further than this page. It would need to be discussed if this is a risk worth taking.

**Comment by Protohedgehog** [comment]
This is a wicked cool idea, and also relates to #26 too.

What we could simply do to reconcile this is adding an executive summary as a PDF link, which then wouldn't take people away from the main body of text.

However, we do run the danger of such prioritisation and filtering potentially also being very subjective, and missing out some key elements. Interested to hear what others think on this one.

**Comment by tosteiner** [comment]
Hi Björn, hi Jon, totally agree with both of your points and I do like the idea of compiling a concise outlook (I think that's what #26 aimed for, too), but would rather try to not fashion it in the way of an executive summary, which in my book is perfectly fine for reports or similar types of documents, but my feeling is that it would run counter to what this our collective approach to a strategy is, don't you think?

As far as I understand it, the strategy's intention is to develop an expansive approach to Open Scholarship in its many facets, and to show what an occupation with the world of Open can entail, hence I think it's perfectly fine that the document is rather detailed and exploratory in a variety of ways... 😃 

Soo, long story short, I guess what I'm saying is that I would opt for an outlook, but not for an exec summary 😉

**Comment by Protohedgehog** [comment]
So we already begin with a 'purpose of this document' section, and want to add a stronger finish too. Just trying to work out what additional value the outlook/summar would add atm, without taking too much away.

**Comment by tosteiner** [comment]
how about we sketch sth out collaboratively over the next few days? I'll write down some early thoughts over the weekend... I think what would really be valuable as a conclusion is to develop further the point of "all of this is not new" ... aka back to the roots, Open Knowledge, Open Science is just Science done right, thoughts about Equity, Sustainability, ... (and please do stop me if this turns out to be too philosophical ;) )

**Comment by brembs** [comment]
As the document states, strategy means "who should do what". As I envisaged it, a summary would list the most important actions that have to take place the soonest for change to begin. IOW, which are the most important things in which corner of the ecosystem that have to change and who needs to do what to bring about these most crucial changes.

For instance, given the acquisition strategies of the publishers, we probably have only 3-4 years left to cancel subscriptions and implement open scholarly standards, before the publishers can offer irresistible turnkey solutions to our institutions, at which point all we have done in the last 25 years will have been in vain (and this document would be dead in the water). Who would have to do what in order to bring this change about in the next 3 or so years?

P.S.: I just remembered that I recently had an idea about a role of funders that I think hasn't been mentioned before:
http://bjoern.brembs.net/2018/11/maybe-try-another-kind-of-mandate/
This is something that, if adopted in a similar way and scale as, e.g., PlanS, could have massive short-term effects.

**Comment by tosteiner** [comment]
Björn, okay, I see - that's an excellent point indeed, and would def. tend more towards an exec summary... How about framing this as an "Immediate Action Plan" or similar and add it right after the "Purpose of this document" section?

and re: your thoughts on a different kind of mandate and open standards (which I fully agree with!): why not add those to the strategy as well?

**Comment by brembs** [comment]
"Immediate action plan" sounds great. I guess placement would depend on the final formatting of the document. It could be also placed similarly to an abstract in a journal article, to whet the appetite for the entire document. Of course, that only works of this is a format we will end up with :-)

I was going to ask if it would make sense to add these items to an updated version.

BTW, I just read that they are revamping the old journal of the German Academy of Sciences:
https://www.leopoldina.org/en/publications/scientific-journals/nova-acta-leopoldina/
They now want to have "living documents" there, where people can comment and update the paper and the focus should be on Enlish-language articles on science policy...

**Comment by Protohedgehog** [comment]
Hey @brembs @tosteiner, any further thoughts on this 'Immediate action plan' idea? Did anyone have a chance to sketch out what this might look like?

**Comment by brembs** [comment]
Depending on how the airline reacts to my requests for an earlier flight after they canceled my flight, I might have some time tomorrow to work on this...

**Comment by Protohedgehog** [comment]
If it's RyanAir or EasyJet, I'll assume this will be ready by tomorrow ;)

**Comment by brembs** [comment]
Lufthansa...

**Comment by tosteiner** [comment]
oh dear, that ✈️  sounds like trouble... re "immediate action plan": could also throw in some bits & pieces later during the weekend... how about we ping pong this over the next few days? @brembs if you find the time, feel free to have a go at it and we'll see how it works out :)

**Comment by brembs** [comment]
I got the earlier flight, so won't have much time. Can't promise anything at this point. But we had an EUA meeting yesterday, where  I presented my proposal for fast action:
http://bjoern.brembs.net/2018/11/maybe-try-another-kind-of-mandate/
slides:
https://www.slideshare.net/brembs/incentives-for-infrastructure-modernization

The attendants confirmed my worst fears: Elsevier will have turnkey open science solutions in likely  less than the 3-5 years I estimated. The people there also suggested that once Elsevier has buy-in to these solutions, it will be near impossible to get standards and guidelines passed that Elsevier would adhere to. This means, if we don't want to end up in the mother of all vendor lock-ins and all our work to be for nothing, we need to have some leverage that at least has the chance to get something going on the 3 year time scale. EUA has the kind of reach here to set something in motion, they said. I can only hope that they will do that. Any connections we have to funders (I can do something with NIH and NSF) would be very valuable to tell them that they need to require compliant text, data and code infrastructure from the institutions they fund.

So much for a "fast action plan" that developed yesterday. More later.

**Comment by Protohedgehog** [comment]
You cannot implement a new regime while the current one maintains power.

Well, I guess we all knew this was coming. And because we don't have organisation, or strategy, we were never going to be able to stop them either.

But yeah, maybe let's think about this for framing the action plan, to decide which elements of the strategy are perhaps most urgent?

**Comment by tosteiner** [comment]
so sorry, but have to shift this a few days back as well...

**Comment by Protohedgehog** [comment]
No worries! Have already pushed the deadline back to the end of the month for revisions :)

**Comment by tosteiner** [comment]
yup, excellent 👍

**Comment by tosteiner** [comment]
@Protohedgehog @brembs I've now begun with a humble try to frame the action plan, and thought it would be good to do this first in a separate md file which can then later be added to the strategy, or externalized in other ways :) 

Here's my first steps: https://github.com/Open-Scholarship-Strategy/site/blob/master/immediate-action-plan.md

Would be glad about your opinions on this, and please feel free to amend, delete, etc. as you see fit - obviously this is an early stage, yet-incomplete thing and needs further work, but I wanted to get the ball rolling here 😉 ⚽️

**Comment by Protohedgehog** [comment]
Brilliant, thanks @tosteiner. Have pulled now and will go through it. @brembs if you get a minute to check this too, that would be epic. I can then create a separate PDF version of this to integrate into the site. Will have to also think about how to best format this for the preprint submission re #50

**Comment by brembs** [comment]
Awesome! Will try to find time to have a look at it tomorrow or Friday!

**Comment by Protohedgehog** [comment]
Perfect, thanks @brembs. I'm going to work on it very shortly, so make sure to pull the latest version first :)

**Comment by Protohedgehog** [comment]
OK, I gave the action plan a going over @tosteiner @brembs - it's down to 2 pages now as a PDF, and I also linked to it in index.md.

**Comment by tosteiner** [comment]
@Protohedgehog Great work, Jon, thank you! I figure this might be boiled down to an even shorter version, let's see what @brembs has to say during the next few days, and maybe we can have this done and done by the end of this week 😃

**Comment by Protohedgehog** [comment]
A one liner consisting of 'Stop giving money to commercial publishers for destroying the system of scholarship. QED.' @brembs @tosteiner

**Comment by brembs** [comment]
OK, I'll have a go at it now. @Protohedgehog 's one-liner should suffice, though.... :-)

**Comment by brembs** [comment]
Shortened it rather massively, as most of the specific points are subsumed by demanding standards and proper investment/divestment.

**Comment by tosteiner** [comment]
@brembs did you push it to the site? can't seem to find any updates here...

**Comment by brembs** [comment]
I do not have write access, so I only forked it. Can create a pull request, if you want.

**Comment by Protohedgehog** [comment]
If you could for now @brembs that would be epic. At dinner now but will upgrade you after 😁

**Comment by brembs** [comment]
Pull request opened.

**Comment by brembs** [comment]
Guten Appetit! :-)

**Comment by tosteiner** [comment]
@Protohedgehog @brembs just a tiny bit offtopic, but would you guys be interested in doing a thang on the Strategy (as well as the Action Plan) at the Open Science Barcamp on March 18? Not sure yet if I'll be able to make it, but would be more than happy to chime in in case you think this is something worth presenting there ;) https://www.eventbrite.com/e/barcamp-open-science-tickets-55216091817

**Comment by Protohedgehog** [comment]
@tosteiner what do you think of @brembs edited version now? If you think it's good, I'll close this issue down.

As for the barcamp, I think I'll be there, but not sure if the strategy is appropriate for the event? Maybe.

**Comment by tosteiner** [comment]
@Protohedgehog re: barcamp - I suppose the more natural thing to do there would be to talk about OSMOOC - FOSTER is proposing a session on "How to deliver an effective Open Science Training?" ;)

**Comment by tosteiner** [comment]
@Protohedgehog and re: action plan - yup, I'm fine with how it is, will look at Björn's comment in the pull request regarding "references, language polishing and perhaps re-ordering of items", but the issue can be closed, I guess 👍

**Comment by Protohedgehog** [comment]
OK, sweet. Can chat about the Barcamp on Slack too. I've just finished integrating the latest edits from #26 and #27 too now.

**Comment by brembs** [comment]
WRT Barcamp: I'm frequently in Berlin, so if I'm there by accident, I could attend, but otherwise I don't travel to such events any more:
http://bjoern.brembs.net/2017/02/open-science-too-much-talk-too-little-action/

**Comment by Protohedgehog** [comment]
Ha, I know the post and completely sympathise, @brembs. If you are in town, maybe just pop by for the 'bar' part then.

**Comment by tosteiner** [comment]
@brembs oh, yes, can absolutely relate
