### ISSUE TITLE
Better TOC

### ISSUE THREAD

**Issue by cMadan** [Open-Scholarship-Strategy/site#44]
As @Protohedgehog pointed out in an email, it would be good if the table of contents (TOC) was a sidebar and stayed visible.

I can work on this, with the idea of changing the template a bit. My current plan would be to use this:
- https://mmistakes.github.io/minimal-mistakes/about/ (see TOC on the right)
- https://shaharkadmiel.github.io/Sticky-TOC-Sidebar/

I'm inclined to make the sidebar be on the left, but otherwise generally following that template and 'fix' it to be sticky.

**Comment by tosteiner** [comment]
@cMadan that sounds great!

**Comment by dannycolin** [comment]
@cMadan FYI, CSS property `position: sticky` isn't well supported yet. (source: https://caniuse.com/#feat=css-sticky). 

For the rest, I think you could simply use Bootstrap (even if the version on the website is a bit outdated) to create a second column on the right for the TOC. :)

**Comment by Protohedgehog** [comment]
Ahh, @cMadan if you could get this to work for the new version that would be legendary! This caused quite a headache a while back now..

**Comment by cMadan** [comment]
Spent some time on this today and I think it's all set. Let me know if you have any suggestions before I submit it as PR.

https://cmadan.github.io/Open-Scholarship-Strategy-site/

**Comment by tosteiner** [comment]
@cMadan wow, that looks fabulous! one minor issue that I'm having on a smaller laptop display is that I'm not able to access the TOC's lower part (from 7 downwards) - not sure if there's any option of making this scrollable? (Here's a [screenshot](https://user-images.githubusercontent.com/41517607/50737595-935eaf00-11cb-11e9-807e-211bb7374041.PNG) for clarification - the main text is easily scrollable down to the end, but the TOC stops at 7.1. ... )

**Comment by cMadan** [comment]
@tosteiner, thanks for including the screenshot! I think the best solution would be to remove the second level headers (e.g., 2.1, 7.1, etc.). 

The way this it's done here, I can't make the TOC scrollable; I can either make it 'sticky' so it stays on the side, or 'not sticky' so it stays at the top but can be scrolled. Since the page is so long, I think being sticky is quite useful--but that's only good if you can actually see the whole thing.

**Comment by dannycolin** [comment]
@cMadan Maybe you could use a `@media` querie on smaller devices to : 

Here's a few solutions : 

- remove `sticky` 
- move it to the top of the page
- move it offcanvas and add a button to trigger it (a bit like a menu on mobile devices)

What do you kind? :)

**Comment by cMadan** [comment]
@dannycolin, that's a good point, thanks! If you make the window narrower, the TOC does automatically pop to being at the top of the page. I could change the threshold for that, so it occurs at a lower width.

@tosteiner, what's the screen resolution on that laptop?

**Comment by tosteiner** [comment]
@cMadan 1920x1080 on a 14'', but with 150% scaling ... when I turn scaling of, it fits perfectly... :) But there's other laptops or tablets that run on resolutions such as 1360x768 or lower - with that, the TOC would become partly lost

**Comment by cMadan** [comment]
@tosteiner, thanks for the details. If you make the window smaller, the code is 'responsive' and moves the TOC to the top, but I'm not sure how the browser's measure of the window width is influenced by the scaling. In other words, it might already be doing that if the resolution was lower, but your case circumvents that because of the scaling. I'll look into it a bit.

**Comment by dannycolin** [comment]
@tosteiner I've tested on my 1366x768 laptop and the TOC scroll works. Did you also scale the page on your 1366x768 laptop?

**Edit**

Oh almost forgot! @cMadan is it possible to add a collapse functionality when the TOC is on top of the text?

**Comment by tosteiner** [comment]
@dannycolin no, scaling was deactivated when I tried other resolutions...

**Comment by cMadan** [comment]
@dannycolin, not sure I follow. If the TOC is at the top, why would you want to collapse it? Do you mean the TOC is *overlapping* with text? I haven't seen that happen...

@tosteiner, it looks like CSS code based on resolution doesn't accomodate scaling well. I'm inclined to suggest that users either disable scaling or make the window narrower in those cases.

**Comment by dannycolin** [comment]
@cMadan the UX reason behind making it collapsible by default would be to ease the navigation on mobile devices.

**Comment by cMadan** [comment]
@dannycolin, otherwise it would just be scrolling down a screen length or so?

**Comment by dannycolin** [comment]
@cMadan Or almost two. That TOC is kind of very long XD. It's also bad for web accessibility because people with disability (e.g. Parkinson disease) will have a hard time not clicking on a link.

**Comment by cMadan** [comment]
Okay, that makes sense. I've now added an option to toggle the TOC visibility.

https://cmadan.github.io/Open-Scholarship-Strategy-site/

**Comment by Protohedgehog** [comment]
This looks really awesome, thanks so much @cMadan for taking the time to do this! And everyone else too for their assistance :)

**Comment by cMadan** [comment]
Thanks for the feedback, @tosteiner and @dannycolin!

@Protohedgehog, I'll wait and see if @dannycolin has any comments on the last edits and then submit this as a PR. :)

**Comment by dannycolin** [comment]
@cMadan cool. It works great! thanks.

**Comment by Protohedgehog** [comment]
Merged the new PR, but got a page build failure.. 

> The page build failed for the `master` branch with the following error:
> 
> No `/docs` folder was found to build GitHub Pages. Check the source setting for this repository. For more information, see https://help.github.com/articles/page-build-failed-missing-docs-folder/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by cMadan** [comment]
@Protohedgehog, I'm pretty sure you weren't using the docs before...

Anyways, if you go in the settings as the first link suggests, you should have the "Source" set to "master branch". (Not "master branch /docs folder".)

**Comment by Protohedgehog** [comment]
Aha, doy. Got it now, thanks @cMadan - this looks excellent! I owe you substantial coffees next time we meet :)
