### ISSUE TITLE
Add a bibliography

### ISSUE THREAD

**Issue by Protohedgehog** [Open-Scholarship-Strategy/site#51]
Maybe divided into sections:
1. Papers etc referenced
2. Tools/services mentioned

**Comment by tosteiner** [comment]
Same point was made over at OSMOOC: How about opening a Zotero group for this?

**Comment by Protohedgehog** [comment]
Could do, @tosteiner. I think it wouldn't take me too long just to do this manually in a bit though.

**Comment by tosteiner** [comment]
I'd be happy to do that and begin sorting through the strategy later this week - I work with the desktop client which makes adding stuff much easier

**Comment by Protohedgehog** [comment]
@tosteiner I'm spending much of today working on this too. Lemme see how much I can get finished, and then what needs to be done after that. Should be able to finish the proofing and bibliography, hopefully.

**Comment by tosteiner** [comment]
@Protohedgehog that's great, thanks! I'm currently tied down with prepping up for a job interview, but will continue with the strategy after Wednesday

**Comment by Protohedgehog** [comment]
Ha, I have one of them over the next couple of days too (sneaky for now). But this takes priority for me.. ;)

**Comment by tosteiner** [comment]
🤞 hey, that's great news - I'll keep my fingers crossed 🍀

**Comment by Protohedgehog** [comment]
OK, first whack here done https://open-scholarship-strategy.github.io/site/#12-references-

Only problem for me is that the TOC section 12 is off the screen now, and part of 11 too. Any idea on how to potentially fix that? @cMadan @tosteiner

**Comment by tosteiner** [comment]
@Protohedgehog when you scroll down the main body of the text, does the TOC follow? I do have the same problem, but suppose it's just too many entries in the TOC to be properly displayed... not sure if this is feasible, but an option would be to add a fold-out for second-level entries, so that only 1-12 show on initial load  and 1.1, 1.2 ... expand after you click on them

**Comment by Protohedgehog** [comment]
Ah yes, if I scroll through the whole document then it does. Yeah, a 'collapsible' menu of sorts might be a nice solution to this, if possible.

**Comment by cMadan** [comment]
@tosteiner, can you think of any websites that do that? I know I've seen that functionality before, but can't recall a place that has it... If I have an example to work from, I can make it work here.

**Comment by tosteiner** [comment]
@cMadan I know this from a variety of forum tools, and what particularly comes to mind is GitBook - see https://docs.gitbook.com/ (TOC on the left), or this [wiki template](https://en.wikipedia.org/wiki/Template:Collapsible_sections_option)

**Comment by cMadan** [comment]
@tosteiner, I was thinking of something that automatically expanded the section you're currently in, as you scroll down. Gitbook seems to just expand the page your currently on, but each is a separate page. The wiki template example is closer, but needs the user to manually expand each section, that should be do-able, but is perhaps a bit more tedious...

For now I'll wait to see if either of us (or someone else) can find an example that auto-expands the current section, but if that doesn't come up, I'll implement something like the wiki example.

**Comment by tosteiner** [comment]
@cMadan oh, I see - hum, I don't think I've come across the auto-expanding variation yet - usually, you're simply shown the main points of the TOC, and when you actively click on one of these, the sub-sections appear... but auto-expansion sounds really fancy!

**Comment by tosteiner** [comment]
@Protohedgehog brilliant work on the biblio and the main text! What would you say, do you think this is now nearing completion so we might think about cleaning up and finalization? I'm particularly asking because I want to also update the German translation to the most current state, and think this might be it ;)  

Also, for the bibliography: I was thinking... would you mind me switching research paper links with DOIs where available? I think this would make re-use more easy, and since DOIs are supposed to be stable, also help with longer-term availability of these references :)

**Comment by Protohedgehog** [comment]
Yes, I think the remaining main things to do are the executive intro as Björn mentioned, and the conclusion section. There are a couple of remaining things in the issues section too that others have mentioned.

Sure, can look at switching to DOIs too. Will add it to the list of things to do this week :)

**Comment by tosteiner** [comment]
@Protohedgehog Got some spare time on my hands today (travel day back to Hamburg), so would work a bit on the action plan thing, and could also throw in the DOIs if that's okay with you?

**Comment by Protohedgehog** [comment]
Brill, thanks @tosteiner! Merged your PR now, all looks good here. I think we just have a couple of bits left to finish that I can work on this week, and then I'll send around the big email again.

**Comment by Protohedgehog** [comment]
Can this be closed now @tosteiner?
