### ISSUE TITLE
Better visualiation of the site

### ISSUE THREAD

**Issue by Protohedgehog** [Open-Scholarship-Strategy/site#8]
Does anyone know of a better way to visualise the content? It's a bit of a long static page at the moment. Just something like having the table of contents stuck to the sidebar might be useful.

**Comment by tosteiner** [comment]
uhm, site is running on GitHub Pages, right? They've got a variety of themes available, see e.g. (w. sidebar):

* https://pages-themes.github.io/minimal/
* https://pages-themes.github.io/dinky/

**Comment by Protohedgehog** [comment]
Oooh, legendary! Thanks Tobias, let's go with dinky and see what happens.

**Comment by tosteiner** [comment]
or (more advanced): https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#github-pages-method

**Comment by Protohedgehog** [comment]
Thanks for your help on this! OK, I just tried to edit the _site.yml to use the dinky theme and broke the website.

Getting the error: Error in navbarHeights[[theme]] : subscript out of bounds

Any idea on how to get past that?

**Comment by tosteiner** [comment]
hm, good question... not exactly sure... you're compiling your text with R, right? There might be some translation issues between R, pandoc and the markdown handler in GitHub, but that's just a (semi-)educated guess based on [this here](https://github.com/rstudio/rmarkdown/issues/1016) - so maybe just try the other theme, Minimal? (sorry, not much help, though 😊 )

**Comment by Protohedgehog** [comment]
Yep, I'm trying to do all of this in R Studio. Minimal doesn't seem to work either, same error.  Reverting back to flatly for now.. Hmmm.

**Comment by tosteiner** [comment]
maybe you want to check this one here: https://github.com/rstudio/rmarkdown/issues/1189 - in short, this comes down to an update of rmarkdown to v1.8 or later (in case you want to try that)

**Comment by Protohedgehog** [comment]
OK, I had 1.9 installed, but upgrading to 1.10 now.. Let's see! :)

**Comment by tosteiner** [comment]
sounds good :) but yeah, in general, I guess someone with deeper knowledge of git would be more helpful than me, I guess... I do know the basics, but am quickly lost when it comes to looking under the hood

**Comment by Protohedgehog** [comment]
OK, that didn't work, sadly. I thought it did for a second but was mistaken. @danielskatz any idea on this stuff?

**Comment by Protohedgehog** [comment]
I think I need to have a config.yml file that might help with some of these things.  Will investigate.

**Comment by tosteiner** [comment]
👍 sounds reasonable, yes  - see https://github.com/pages-themes/dinky/blob/master/README.md for more

**Comment by danielskatz** [comment]
Sorry, this isn't one of the things I have  lot of experience with

**Comment by zuphilip** [comment]
There is a Jekyll plugin for the TOC you might want to look closer into: https://github.com/dafi/jekyll-toc-generator. However, it seems that you then need to overwrite some of the files locally. Because I have only seen in the one pre-defined theme a TOC: https://pages-themes.github.io/leap-day/

**Comment by tosteiner** [comment]
@Protohedgehog playing around with github page themes, I managed to apply basic, out-of-the-box styling - this is the `Architect` theme at my fork at https://tosteiner.github.io/site/

**Comment by Protohedgehog** [comment]
Awesome, I got the pull request here: https://github.com/Open-Scholarship-Strategy/site/pull/14

Will have to work on this tomorrow, as it looks like there are a few conflicts. Thanks again! :)

**Comment by jaranta** [comment]
Just a heads up: you can only use a couple of pre-approved Jekyll plugins if you host your site on Github Pages (jekyll-toc-generator warns about this). You can pretty easily build this with just Liquid, though. I have some experience playing around with Jekyll, so I can help with this if you have some specific things in mind.

**Comment by Protohedgehog** [comment]
Hi @jaranta, thanks for this helpful comment! Should have figured things were limited.  

If you know how though, the sort of thing I think we're after is like here: https://open-science-training-handbook.gitbook.io/book/introduction with the table of contents as a static item in the sidebar as you scroll through the document. Is something like that possible..? :)

**Comment by jaranta** [comment]
Yes it is! You just have to create the TOC when creating the document and then do some CSS trickery to push it to either side of the document. Shouldn't be even that hard. You could get it to highlight the relevant section in the TOC with some more trickery, but that's probably beyond me.

Caveat: I'm not an expert in any of this, but I'd be happy to tackle the challenge. I can try it locally and push a working version as soon as I have one, if you're not in a hurry.

**Comment by Protohedgehog** [comment]
Aha, I see, thanks! The highlighting thing would be cool too, if possible. 

I'm looking at posts like here https://github.com/dafi/jekyll-toc-generator and here https://kramdown.gettalong.org/converter/html.html#toc for now, but it seems like some extra files and stuff are needed that we don't have yet. Please do feel free to take a whack at it if you find the time - no rush at all! :)

**Comment by dannycolin** [comment]
@Protohedgehog There's an other solution I can think of. You could have two branches. One for the source code of the jekyll website and an other for the `_site` folder. You'll need to configure the repository so it looks to the branch containing the `_site` folder instead of the one containing the source. 

I can create a test repository during the weekend because I don't remember all the steps in detail. If it still works I'll let you know ;).

**Comment by borisalmonacid** [comment]
I used the sphinx-doc for generated a different extension using markdown files.

The output with sphinx are:
- HTML (including Windows HTML Help)
- LaTeX (for printable PDF versions)
- ePub
- Texinfo
- manual pages
- plain text

You can check the examples in this url [Sphinx Examples](http://www.sphinx-doc.org/en/master/examples.html)
Do you need something like that to generate different outputs?

**Comment by rijdho** [comment]
Yep but the problem was with the jupyter notebook file :(

__
Laboratorio de Métodos
I3S // Facultad de Ciencias de la Salud
Universidad Central de Chile
Of: (+56)226661609
ORCID: 0000-0001-5058-9309

**Comment by borisalmonacid** [comment]
@ametodico this problem is solved with -> https://help.github.com/articles/working-with-jupyter-notebook-files-on-github/

**Comment by Protohedgehog** [comment]
@dannycolin If you get the chance to give that a stab, I'd deeply appreciate it! 

@borisalmonacid - most of these formats exist already here: https://zenodo.org/record/1323437#.W2e2lij7RPY - do you think more types need to be added for the next release?

Also, this viewer thing looks mint. Lemme see if I can add a fix for that, thanks!

**Comment by tosteiner** [comment]
this does kind of feed into this here - #44

**Comment by cMadan** [comment]
I think #44 sorted all this out?

**Comment by Protohedgehog** [comment]
Yes, thanks @cMadan! Great work, everyone :)
